#ifndef ENVIRONMENT_H_DEFINED
#define ENVIRONMENT_H_DEFINED

//   ---   Definition Constants   ---
//Square constants
//Void square constant
#define VOD 0x00
//Collider square constant
#define COL 0x01

//   ---   Environment Constants   ---
//Map
#define WIDTH 17
#define HEIGHT 19
const uint8_t[WIDTH][HEIGHT] =
{
    {COL,COL,COL,COL,COL,COL,COL,COL,COL,COL,COL,COL,COL,COL,COL,COL,COL},
    {COL,VOD,VOD,VOD,VOD,VOD,VOD,VOD,COL,VOD,VOD,VOD,VOD,VOD,VOD,VOD,COL},
    {COL,VOD,COL,COL,VOD,COL,COL,VOD,COL,VOD,COL,COL,VOD,COL,COL,VOD,COL},
    {COL,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,COL},
    {COL,VOD,COL,COL,VOD,COL,VOD,COL,COL,COL,VOD,COL,VOD,COL,COL,VOD,COL},
    {COL,VOD,VOD,VOD,VOD,COL,VOD,VOD,COL,VOD,VOD,COL,VOD,VOD,VOD,VOD,COL},
    {COL,COL,COL,COL,VOD,COL,COL,VOD,COL,VOD,COL,COL,VOD,COL,COL,COL,COL},
    {COL,COL,COL,COL,VOD,COL,VOD,VOD,VOD,VOD,VOD,COL,VOD,COL,COL,COL,COL},
    {VOD,VOD,VOD,VOD,VOD,VOD,VOD,COL,COL,COL,VOD,VOD,VOD,VOD,VOD,VOD,VOD},
    {COL,COL,COL,COL,VOD,COL,VOD,VOD,VOD,VOD,VOD,COL,VOD,COL,COL,COL,COL},
    {COL,COL,COL,COL,VOD,COL,VOD,COL,COL,COL,VOD,COL,VOD,COL,COL,COL,COL},
    {COL,VOD,VOD,VOD,VOD,VOD,VOD,VOD,COL,VOD,VOD,VOD,VOD,VOD,VOD,VOD,COL},
    {COL,VOD,COL,COL,VOD,COL,COL,VOD,COL,VOD,COL,COL,VOD,COL,COL,VOD,COL},
    {COL,VOD,VOD,COL,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,COL,VOD,VOD,COL},
    {COL,COL,VOD,COL,VOD,COL,VOD,COL,COL,COL,VOD,COL,VOD,COL,VOD,COL,COL},
    {COL,VOD,VOD,VOD,VOD,COL,VOD,VOD,COL,VOD,VOD,COL,VOD,VOD,VOD,VOD,COL},
    {COL,VOD,COL,COL,COL,COL,COL,VOD,COL,VOD,COL,COL,COL,COL,COL,VOD,COL},
    {COL,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,VOD,COL},
    {COL,COL,COL,COL,COL,COL,COL,COL,COL,COL,COL,COL,COL,COL,COL,COL,COL}
}
//out of map (out of index) squares
const uint8_t OUT_OF_MAP_SQURES = COL;

//2D environmental direction
typedef enum EnvDirection
{
    N = 0x01,
    E = 0x02,
    S = 0x04,
    W = 0x08
} EnvDirection_t;

//Functions
uint8_t getEnvironmentByCoordinate(uint);

#endif // ENVIRONMENT_H_DEFINED
